#!/usr/bin/env bash


### /etc/sysctl.conf
if ! grep -q "fs.inotify.max_user_watches=" "/etc/sysctl.conf"; then
    echo "fs.inotify.max_user_watches=524288" >> "/etc/sysctl.conf"
    sysctl -p
fi
if ! grep -q "vm.max_map_count=" "/etc/sysctl.conf"; then
    echo "vm.max_map_count=262144" >> "/etc/sysctl.conf"
    sysctl -p
fi
if ! grep -q "vm.swappiness=" "/etc/sysctl.conf"; then
    echo "vm.swappiness=1" >> "/etc/sysctl.conf"
    sysctl -p
fi
###

### /etc/dnf/dnf.conf
if ! grep -q "fastestmirror=" "/etc/dnf/dnf.conf"; then
    echo "fastestmirror=True" >> "/etc/dnf/dnf.conf"
fi
if ! grep -q "max_parallel_downloads=" "/etc/dnf/dnf.conf"; then
    echo "max_parallel_downloads=10" >> "/etc/dnf/dnf.conf"
fi
if ! grep -q "keepcache=" "/etc/dnf/dnf.conf"; then
    echo "keepcache=True" >> "/etc/dnf/dnf.conf"
fi
if ! grep -q "metadata_timer_sync=" "/etc/dnf/dnf.conf"; then
    echo "metadata_timer_sync=0" >> "/etc/dnf/dnf.conf"
fi
###

### DNS configuration - unbound
if ! command -v unbound > /dev/null 2>&1; then
  dnf install -y unbound
fi
if ! command -v dnssec-triggerd > /dev/null 2>&1; then
  dnf install -y dnssec-trigger
fi
echo -e "[main]\ndns=unbound" > /etc/NetworkManager/conf.d/dns.conf
if ! [ -e /etc/unbound/conf.d/dns-over-tls.conf ]; then
cat <<EOT > /etc/unbound/conf.d/dns-over-tls.conf
server:
    tls-cert-bundle: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 8.8.8.8@853#dns.google
    forward-addr: 8.8.4.4@853#dns.google
EOT
fi
systemctl disable --now systemd-resolved
systemctl enable --now unbound
systemctl enable --now dnssec-triggerd
systemctl restart unbound
systemctl restart dnssec-triggerd
systemctl restart NetworkManager
###
