#!/usr/bin/env bash

### /etc/dnf/dnf.conf
#if ! grep -q "fastestmirror=" "/etc/dnf/dnf.conf"; then
#    echo "fastestmirror=True" >> "/etc/dnf/dnf.conf"
#fi
#if ! grep -q "max_parallel_downloads=" "/etc/dnf/dnf.conf"; then
#    echo "max_parallel_downloads=10" >> "/etc/dnf/dnf.conf"
#fi
#if ! grep -q "keepcache=" "/etc/dnf/dnf.conf"; then
#    echo "keepcache=True" >> "/etc/dnf/dnf.conf"
#fi
#if ! grep -q "metadata_timer_sync=" "/etc/dnf/dnf.conf"; then
#    echo "metadata_timer_sync=0" >> "/etc/dnf/dnf.conf"
#fi
###

### /etc/sysctl.conf
if ! grep -q "fs.inotify.max_user_watches=" "/etc/sysctl.conf"; then
    echo "fs.inotify.max_user_watches=524288" >> "/etc/sysctl.conf"
fi
if ! grep -q "vm.max_map_count=" "/etc/sysctl.conf"; then
    echo "vm.max_map_count=262144" >> "/etc/sysctl.conf"
fi
sysctl -p
###

### install base packages
dnf install -y htop git-all most cascadia-code-fonts tmux breeze-gtk
###

### install yakuake dropdown terminal and starship shell prompt
dnf install -y yakuake starship fish
ln -s -t /etc/xdg/autostart /usr/share/applications/org.kde.yakuake.desktop
###

### setup git
git config --global status.submoduleSummary true
git config --global diff.submodule log
git config --global commit.verbose true
###

### setup vim as default editor
sudo dnf install -y vim
sudo dnf remove -y nano
echo '[ -z "$EDITOR" ] && export EDITOR="/usr/bin/vim"' > /etc/profile.d/vim-default-editor.sh
###

## install docker and docker-compose
# dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
# dnf install -y docker-ce docker-compose
# https://github.com/moby/moby/issues/41230
# dnf install -y policycoreutils-python-utils && semanage permissive -a iptables_t
# loginctl enable-linger "$(logname)"
# run as user
# dockerd-rootless-setuptool.sh install
# systemctl enable --user --now docker
# export DOCKER_HOST=unix:///run/user/1000/docker.sock
# append to /etc/security/limits.conf
#   gb              soft    memlock         unlimited
#   gb              hard    memlock         unlimited
# ###

## install podman and docker-compose
dnf install -y podman podman-docker docker-compose
if ! grep -qF "label = false" /usr/share/containers/containers.conf; then
  sed -i '/label =/a label = false' /usr/share/containers/containers.conf
fi

if ! grep -qF 'unqualified-search-registries = ["docker.io"]' /etc/containers/registries.conf; then
  sed -i '/unqualified-search-registries =/a unqualified-search-registries = ["docker.io"]' /etc/containers/registries.conf
fi
###

# ### RPMFusion and multimedia codecs
# dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
# dnf check-update --refresh
# dnf groupupdate -y core
# dnf groupupdate -y multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
# dnf groupupdate -y sound-and-video
# dnf install -y rpmfusion-free-release-tainted
# dnf install -y libdvdcss
# ###

### fix nouveau brightness
if lspci | grep -Eq 'NVS 5400M|GF108M' ; then
grubby --update-kernel=ALL --args="acpi_backlight=video"
fi
###

### fix TrackPoint Keyboard II middle button
# if xinput list | grep "TrackPoint Keyboard II Mouse" ; then
# xinput set-button-map "TrackPoint Keyboard II Mouse" 1 0
# fi
###

### tlp
sudo dnf install -y tlp
cat <<EOF > /etc/tlp.d/01-thresholds.conf
START_CHARGE_THRESH_BAT0=40
STOP_CHARGE_THRESH_BAT0=70
EOF
###

### entr
sudo dnf install -y xdotool the_silver_searcher entr
###

# ### media player (requires rpmfusion)
# sudo dnf install -y mpv mpv-mpris
# ###

## Google Chrome
rpm --import https://dl-ssl.google.com/linux/linux_signing_key.pub
dnf -y install https://dl.google.com/linux/direct/google-chrome-stable_current_$(uname -i).rpm
##

## Visual Studio Code
rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo
dnf -y install code
##

# ### DNS configuration
mkdir -p /etc/systemd/resolved.conf.d/
cat <<EOF > /etc/systemd/resolved.conf.d/dns_over_tls.conf
[Resolve]
DNS=185.180.206.110#gbdns.ga
DNSOverTLS=yes
Domains=~.
EOF
systemctl restart systemd-resolved
# ###

# SDDM external monitors
# copy xrandr w args from arandr to /etc/sddm/Xsetup
