#!/usr/bin/env ruby

require 'fileutils'
require 'pathname'

# Recursively link files from source to target directory
def linkify source_pn, target_dir_pn
  source_pn.children.each do |child_pn|
    target_pn = target_dir_pn + child_pn.basename
    if child_pn.directory?
      FileUtils.mkdir_p target_pn
      linkify child_pn, target_pn
    else
      FileUtils.ln_s child_pn, target_pn, force: true
    end
  end
end

linkify Pathname(__dir__) + 'home', Pathname(ENV['HOME'])
